export const BANGALORE_COLLEGES = [
  "RV College of Engineering",
  "PES University",
  "BMS College of Engineering",
  "MS Ramaiah Institute of Technology",
  "Christ University",
  "St. Joseph’s College",
  "Dayananda Sagar College of Engineering",
  "Alliance University",
  "CMR Institute of Technology",
  "Jain University",
  "Oxford College of Engineering",
  "Reva University",
  "SVIT Bangalore",
  "Acharya Institute of Technology",
  "East Point College of Engineering",
  "New Horizon College of Engineering",
  "NITTE Meenakshi Institute of Technology",
  "Presidency University",
  "HKBK College of Engineering",
  "Global Academy of Technology",
  "APS College of Engineering",
  "Bangalore Institute of Technology",
  "T John Institute of Technology",
  "Rajarajeswari College of Engineering",
  "Sapthagiri College of Engineering",
  "AMC Engineering College",
  "Garden City University",
  "Mount Carmel College",
  "Kristu Jayanti College",
  "Indian Academy Degree College",
  "Surana College",
  "Bangalore University",
  "Dr Ambedkar Institute of Technology",
  "Don Bosco Institute of Technology",
  "Brindavan College",
  "GITAM School of Technology",
  "KLE Society’s College",
  "Sambhram Institute of Technology",
  "Vemana Institute of Technology",
  "MVJ College of Engineering",
  "BMS Institute of Technology",
  "Sri Krishna Institute of Technology",
  "Sri Venkateshwara College of Engineering",
  "City Engineering College",
  "Imad Basha College",
  "Al-Ameen College",
  "St. Francis College",
  "Kristu Jayanti Autonomous College",
  "JSS Academy of Technical Education",
  "HKBK Degree College",
  "Jyoti Nivas College",
  "Vydehi Institute of Technology",
  "Gopalan College of Engineering and Management",
  "Bishop Cotton Women’s Christian College",
  "Oxford Degree College",
  "Presidency College",
  "St. Claret College",
  "NMKRV College",
  "MES College of Arts, Commerce & Science",
  "Other"
];
